
# Nombre del flujo de trabajo
name: CI/CD

# Definir cu치ndo se ejecutar치 el flujo de trabajo
on:
  push:
    branches:
      - master

# Trabajo principal del flujo de trabajo
jobs:
  build-and-push:
    # Sistema operativo para ejecutar el trabajo
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el c칩digo del repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Iniciar sesi칩n en Docker Hub
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Paso 3: Construir y etiquetar la imagen de Docker
    - name: Build and tag Docker image
      run: docker build -t damiankaio/web-d17:latest .
      working-directory: ./

    # Paso 4: Subir la imagen de Docker a Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push damiankaio/web-d17:latest
