name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Lint Dockerfile
      run: |
        docker pull hadolint/hadolint
        docker run --rm -i hadolint/hadolint < app/Dockerfile

    - name: Analyze Vulnerabilities
      run: |
        docker pull aquasec/trivy
        docker run --rm -v $PWD:/app -w /app aquasec/trivy --exit-code 1 --severity HIGH,CRITICAL

    - name: Security Testing
      run: |
        node scripts/security-test.js
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag Docker image
      run: docker build -t damiankaio/my-docker-image-d17:latest .
      working-directory: ./my-app
      

    - name: Push Docker image to Docker Hub
      run: docker push damiankaio/my-docker-image-d17:latest
